spring:
  application:
    name: service-order
  profiles:
    active: dev # 默认激活dev环境
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:dev} # 默认加载nacos里面的dev命名空间的配置
        file-extension: properties # 配置文件后缀名为properties
        group: order # 加载nacos里面的order分组的配置
  config:
    import:
      - classpath:application-feign.yml # 导入feign配置
      - classpath:application-database.yml # 导入数据库配置
      - classpath:application-seata.yml # 导入seata配置

logging:
  level:
    com.company.order.feign: debug

server:
  port: 8009

---
spring:
  config:
    import:
      - nacos:service-order.properties
      - nacos:common.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:service-order.properties
      - nacos:common.properties
    activate:
      on-profile: test