seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${spring.cloud.nacos.server-addr}
      group : "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
      context-path: ""
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
