# 文件名: .github/workflows/maven-separate-deployment-ci-cd.yml

name: Maven Multi-Service Docker CI/CD

on:
  push:
    branches:
      - main
  #pull_request:
   # branches:
    #  - main

env:
  # 定义一个用于镜像的通用仓库前缀
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }} # 你的GitHub用户名或组织名

jobs:
  build: # CI Job - 构建和测试所有模块，并构建/推送Docker镜像
    runs-on: ubuntu-latest # CI 依然使用 GitHub 托管的 Ubuntu Runner
    permissions:
      contents: read
      packages: write # 需要写入 GitHub Packages (ghcr.io) 的权限

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven # 开启Maven依赖缓存

      - name: Build All Services with Maven # 构建所有服务，生成JAR包
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true # 跳过测试以加快构建，测试可以在单独的Job中

      - name: Set up Docker Buildx # 设置Docker构建环境，支持多平台构建
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry # 登录到ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token进行认证

      # --- 构建并推送 Gateway 服务的 Docker 镜像 ---
      - name: Build and Push Gateway Docker Image
        uses: docker/build-push-action@v5
        with:
          context: gateway/ # Dockerfile所在的目录
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cloud-demo/gateway:${{ github.sha }} # 镜像标签
          cache-from: type=gha,scope=gateway-build # 使用GitHub Actions缓存，加快后续构建
          cache-to: type=gha,scope=gateway-build,mode=max

      # --- 构建并推送 Service Order 服务的 Docker 镜像 ---
      - name: Build and Push Service Order Docker Image
        uses: docker/build-push-action@v5
        with:
          context: services/service-order/ # Dockerfile所在的目录
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cloud-demo/service-order:${{ github.sha }}
          cache-from: type=gha,scope=service-order-build
          cache-to: type=gha,scope=service-order-build,mode=max

      # --- 构建并推送 Service Product 服务的 Docker 镜像 ---
      - name: Build and Push Service Product Docker Image
        uses: docker/build-push-action@v5
        with:
          context: services/service-product/ # Dockerfile所在的目录
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cloud-demo/service-product:${{ github.sha }}
          cache-from: type=gha,scope=service-product-build
          cache-to: type=gha,scope=service-product-build,mode=max

  deploy-gateway: # 独立部署 Gateway 服务
    needs: build
    runs-on: self-hosted # 自托管 Runner，运行在你的 Windows 本机上
    permissions:
      contents: read
      packages: read # 需要读取 GitHub Packages (ghcr.io) 的权限

    steps:
      - name: Log in to GitHub Container Registry # CD Job 同样需要登录才能拉取私有镜像
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Run Gateway Docker Image
        run: |
          $IMAGE_TAG = "${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cloud-demo/gateway:${{ github.sha }}"
          $CONTAINER_NAME = "cloud-demo-gateway-container" # 为容器定义一个固定名称
          $PORT_MAP = "8080:80" # 容器内部端口:宿主机端口，根据Gateway实际端口修改
          
          Write-Host "--- Start Deploy Gateway Script ---"
          Write-Host "Image Tag to pull: $IMAGE_TAG"
          Write-Host "Container Name: $CONTAINER_NAME"
          Write-Host "Port Mapping: $PORT_MAP"
          
          # 1. 拉取最新 Docker 镜像
          Write-Host "Pulling Docker image..."
          try {
              docker pull $IMAGE_TAG | Out-Host # 将docker pull的输出显示在日志中
              Write-Host "Image pulled successfully."
          } catch {
              Write-Host "Error pulling image: $($_.Exception.Message)"
              exit 1
          }
          
          # 2. 停止并移除旧的容器（如果存在）
          Write-Host "Attempting to stop and remove existing container '$CONTAINER_NAME'..."
          # docker stop/rm 可能会在容器不存在时报错，使用 -ErrorAction SilentlyContinue 避免Job失败
          # 停止容器（如果正在运行），|| true 确保即使停止失败（如容器不存在）也不会中断脚本
          docker stop $CONTAINER_NAME || true
          # 移除容器（如果存在），|| true 确保即使移除失败也不会中断脚本
          docker rm $CONTAINER_NAME || true
          Write-Host "Existing container stopped and removed (if it existed)."
          
          # 3. 运行新的容器
          Write-Host "Running new container '$CONTAINER_NAME'..."
          try {
              docker run -d --name $CONTAINER_NAME -p $PORT_MAP $IMAGE_TAG | Out-Host # -d 后台运行
              Write-Host "New container started successfully."
          } catch {
              Write-Host "Error starting container: $($_.Exception.Message)"
              exit 1
          }
          
          Write-Host "--- End Deploy Gateway Script ---"
          Write-Host "Gateway service deployed via Docker. Check 'docker ps' for status."

  deploy-service-order: # 独立部署 Service Order 服务
    needs: build
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Run Service Order Docker Image
        run: |
          $IMAGE_TAG = "${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cloud-demo/service-order:${{ github.sha }}"
          $CONTAINER_NAME = "cloud-demo-order-container"
          $PORT_MAP = "8080:8009" # 假设Order服务监听8081，请根据实际情况修改
          
          Write-Host "--- Start Deploy Service Order Script ---"
          Write-Host "Image Tag to pull: $IMAGE_TAG"
          Write-Host "Container Name: $CONTAINER_NAME"
          Write-Host "Port Mapping: $PORT_MAP"
          
          docker pull $IMAGE_TAG | Out-Host
          # 停止容器（如果正在运行），|| true 确保即使停止失败（如容器不存在）也不会中断脚本
          docker stop $CONTAINER_NAME || true
          # 移除容器（如果存在），|| true 确保即使移除失败也不会中断脚本
          docker rm $CONTAINER_NAME || true
          docker run -d --name $CONTAINER_NAME -p $PORT_MAP $IMAGE_TAG | Out-Host
          
          Write-Host "--- End Deploy Service Order Script ---"
          Write-Host "Service Order deployed via Docker. Check 'docker ps' for status."

  deploy-service-product: # 独立部署 Service Product 服务
    needs: build
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Run Service Product Docker Image
        run: |
          $IMAGE_TAG = "${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cloud-demo/service-product:${{ github.sha }}"
          $CONTAINER_NAME = "cloud-demo-product-container"
          $PORT_MAP = "8080:9000" # 假设Product服务监听8082，请根据实际情况修改
          
          Write-Host "--- Start Deploy Service Product Script ---"
          Write-Host "Image Tag to pull: $IMAGE_TAG"
          Write-Host "Container Name: $CONTAINER_NAME"
          Write-Host "Port Mapping: $PORT_MAP"
          
          docker pull $IMAGE_TAG | Out-Host
          # 停止容器（如果正在运行），|| true 确保即使停止失败（如容器不存在）也不会中断脚本
          docker stop $CONTAINER_NAME || true
          # 移除容器（如果存在），|| true 确保即使移除失败也不会中断脚本
          docker rm $CONTAINER_NAME || true
          docker run -d --name $CONTAINER_NAME -p $PORT_MAP $IMAGE_TAG | Out-Host
          
          Write-Host "--- End Deploy Service Product Script ---"
          Write-Host "Service Product deployed via Docker. Check 'docker ps' for status."